Continuation of curator work and start on github image hosting.

diff --git a/setup-env b/setup-env
--- a/setup-env
+++ b/setup-env
@@ -1,8 +1,10 @@
-
+#! /bin/bash
 # Clone and customize this for your deployment
 #
 # NOTE:  must be sourced from jupyterhub-deploy root directory
 #
+
+# set -eu # DO NOT 'set -eu' since this script is sourced and will kill the sourcing terminal/shell on error.
 
 # ----------------- basic inputs,  must set for deployment --------------
 
@@ -21,6 +23,9 @@ export PLATFORM=linux/amd64
 
 # Set to "" (empty) for source build,  or quay.io/jupyter/ for current docker-stacks image.
 # jupyter is now at quay.io/jupyter/  needed to obtain fresh builds.  trailing backslash required
+
+
+
 export REGISTRY=""
 # export REGISTRY=""
 
@@ -31,12 +36,20 @@ export REGISTRY=""
 export OWNER=spacetelescope
 # export OWNER=spacetelescope
 
-export BASE_NOTEBOOK=minimal-notebook
+export BASE_NOTEBOOK=scipy-notebook
 
 export BASE_IMAGE=${OWNER}/${BASE_NOTEBOOK}
 
 export NOTEBOOK_TAG=latest
 export NOTEBOOK_ID=notebook-${DEPLOYMENT_NAME}:${NOTEBOOK_TAG}  # abstract name of mission-specific notebook image
+
+
+export DATE_TAG=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+export GITHUB_REGISTRY=""
+export GITHUB_REPO=spacetelescope/science-platform-images
+export GITHUB_TAG=notebook-${DEPLOYMENT_NAME}-${DATE_TAG}
+export GITHUB_IMAGE_ID=${GITHUB_REGISTRY}/${GITHUB_REPO}:${GITHUB_TAG}
+
 
 export UBUNTU_TAG="24.04"            # # Image scanning,  report Ubuntu status for this version of Ubuntu
 
