Work on image-scan and build-wrangler scan-result-tagging

diff --git a/.github/workflows/build-wrangler.yml b/.github/workflows/build-wrangler.yml
--- a/.github/workflows/build-wrangler.yml
+++ b/.github/workflows/build-wrangler.yml
@@ -93,21 +93,6 @@ jobs:
            scripts/image-test
            df -h
 
-      - name: Image Push
-        shell: bash
-        run: |
-            set -o pipefail
-            set -x
-            # source setup-env
-            df -h
-            export NBW_WRANGLER_SPEC=$(find nbw-spec-archive/ -name "*.yaml" -type f | head -1)
-            export GITHUB_TAG=$(basename ${NBW_WRANGLER_SPEC} .yaml)
-            export BUILT_IMAGE_HASH=$(docker image ls | head -2 | awk '{print $3;}' | tail -1)
-            export GITHUB_UNTAGGED_ID=ghcr.io/${{ github.repository }}
-            export GITHUB_IMAGE_ID=${GITHUB_UNTAGGED_ID}:${GITHUB_TAG}
-            docker tag ${BUILT_IMAGE_HASH} ${GITHUB_IMAGE_ID}
-            docker push $GITHUB_IMAGE_ID
-
        # strictly speaking in prod we shold scan before pushing,  this is for trivy testing
       - name: Run Trivy vulnerability scanner
         shell: bash
@@ -118,4 +103,21 @@ jobs:
           export BUILT_IMAGE_HASH=$(docker image ls | head -2 | awk '{print $3;}' | tail -1)
           export GITHUB_UNTAGGED_ID=ghcr.io/${{ github.repository }}
           export GITHUB_IMAGE_ID=${GITHUB_UNTAGGED_ID}:${GITHUB_TAG}
-          image-scan  $GITHUB_IMAGE_ID  --yes
+          image-scan  $GITHUB_IMAGE_ID  --yes  on-github   # writes to /tmp/trivy-tag
+          # only fails on scanning script errors, not HIGH or CRITICALS
+          # which result in:  hasfixed, hasunfixed, scanok
+
+      - name: Image Push
+        shell: bash
+        run: |
+            set -o pipefail
+            set -x
+            # source setup-env
+            df -h
+            export NBW_WRANGLER_SPEC=$(find nbw-spec-archive/ -name "*.yaml" -type f | head -1)
+            export GITHUB_TAG=$(basename ${NBW_WRANGLER_SPEC} .yaml)-$(cat /tmp/trivy-tag)
+            export BUILT_IMAGE_HASH=$(docker image ls | head -2 | awk '{print $3;}' | tail -1)
+            export GITHUB_UNTAGGED_ID=ghcr.io/${{ github.repository }}
+            export GITHUB_IMAGE_ID=${GITHUB_UNTAGGED_ID}:${GITHUB_TAG}
+            docker tag ${BUILT_IMAGE_HASH} ${GITHUB_IMAGE_ID}
+            docker push $GITHUB_IMAGE_ID
diff --git a/scripts/image-scan b/scripts/image-scan
--- a/scripts/image-scan
+++ b/scripts/image-scan
@@ -5,8 +5,7 @@ set -e
 # If desired,  $1 can override the default image type
 export IMAGE_ID=${1:-${NOTEBOOK_ID}}
 export AGREE_TO_INSTALL=${2:-""}
-
-printenv | sort
+export WHERE=${3:-""}
 
 # image-login
 
@@ -40,9 +39,49 @@ fi
 
 # docker run -v /var/run/docker.sock:/var/run/docker.sock \
 #       public.ecr.aws/aquasecurity/trivy:latest \
-${TRIVY}  image ${IMAGE_ID} \
+
+function f_trivy {
+    PARAMS=$@
+    ${TRIVY}  image ${IMAGE_ID} \
+       ${PARAMS} \
        --timeout 30m \
        --severity HIGH,CRITICAL \
        --scanners vuln \
        --pkg-types os,library \
        --exit-code 1
+    return $?
+}
+
+function annotated_echo {
+    if [[ $WHERE == "on-github" ]]; then
+        ANN_PREFIX="::warning "
+        echo "::warning $*"
+    else
+        echo "$*"
+    fi
+}
+
+echo "scanfailed" >/tmp/trivy-tag   # this may be impossible but just in case
+
+set -o pipefail         # do not stop if f_trivy fails in a pipe
+set +e                  # do not stop on error
+
+# Run Trivy and suppress initial output until Legend: is seen
+f_trivy | awk '/^Legend:/ {found=1} found {print}'
+
+if [ $? -ne 0 ]; then
+    annotated_echo "===> Trivy scan FAILED w/o --ignore-unfixed."
+    OUTPUT=$(f_trivy --ignore-unfixed)
+    if [ $? -ne 0 ]; then
+        annotated_echo "===> Trivy scan FAILED with --ignore-unfixed."
+        echo "hasunfixed" >/tmp/trivy-tag
+    else
+        annotated_echo "===> Trivy scan PASSED with --ignore-unfixed."
+        echo "hasfixed" >/tmp/trivy-tag
+    fi
+else
+    echo "===> Trivy scan PASSED even w/o --ignore-unfixed."
+    echo "scanok" >/tmp/trivy-tag
+fi
+
+exit 0
